server:
  port: 8307
spring:
  application:
    name: feign-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
feign:
  hystrix:
    enabled: true
logging:
  level:
    com.soiree.springcloud.feignserver.service.FeignService: debug