server:
  port: 8201
spring:
  application:
    name: feign-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@localhost:8002/eureka/,http://root:root@kubernetes.docker.internal:8003/eureka/ #配置注册中心地址
feign:
  hystrix:
    enabled: true
logging:
  level:
    com.soiree.springcloud.feignserver.service.FeignService: debug