server:
  port: 8002
spring:
  security:
    user:
      name: root
      password: root
  application:
    name: eureka-server1
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true  #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true #指定是否要注册到注册中心（注册中心不需要开启）
    service-url:
      defaultZone: http://root:root@kubernetes.docker.internal:8003/eureka/ #注册到另一个Eureka注册中心

