server:
  port: 8402
spring:
  profiles:
    active: dev
  application:
    name: config-client
  cloud:
    discovery:
      service-id: config-server
    override-none: true
eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://root:root@localhost:8002/eureka/,http://root:root@kubernetes.docker.internal:8003/eureka/ #配置注册中心地址


