server:
  port: 8080
spring:
  datasource:
    url:  jdbc:mysql://localhost:6666/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: soiree
    druid:
    initial-size: 5 #连接池初始化大小
    min-idle: 10 #最小空闲连接数
    max-active: 20 #最大连接数
    web-stat-filter:
    exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
    stat-view-servlet: #访问监控网页的登录用户名和密码
    login-username: druid
    login-password: druid
mybatis:
  mapper-locations:
    classpath*:  com/soiree/swagger/mapper/*.xml
#logging:
    ##  level:
    ##    root: DEBUG #指定包，指定类，或者直接root  #root: debug