server:
  port: 8080
spring:
  datasource:
#    url:  jdbc:mysql://localhost:6666/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url:  jdbc:mysql://localhost:5555/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #使用容器，请更改  jdbc:mysql://mysql:5555   需要容器在同一个network下或link mysql
    username: root
    password: soiree
    druid:
    initial-size: 5 #连接池初始化大小
    min-idle: 10 #最小空闲连接数
    max-active: 20 #最大连接数
    web-stat-filter:
    exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
    stat-view-servlet: #访问监控网页的登录用户名和密码
    login-username: druid
    login-password: druid
    credit:
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      time-between-eviction-runs-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      prod:
        min-evictable-idle-time-millis: 1800000
        test-while-idle: true
        time-between-eviction-runs-millis: 300000
        validation-query: SELECT 1 FROM DUAL
  mvc:
    async:
      request-timeout: 20000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: soiree
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100
mybatis:
  mapper-locations:
    classpath*:  com/soiree/swagger/mapper/*.xml
#logging:   #如已使用了配置文件，请注释掉
    ##  level:
    ##    root: DEBUG #指定包，指定类，或者直接root  #root: debug






