server:
  port: 8080
  tomcat:
    max-connections: 20000
spring:
  datasource:
#    url:  jdbc:mysql://localhost:6666/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url:  jdbc:mysql://localhost:5555/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #使用容器，请更改  jdbc:mysql://mysql:5555   需要容器在同一个network下或link mysql

    druid:
      username: root
      password: soiree
      
  mvc:
    async:
      request-timeout: 20000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: soiree
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100
mybatis:
  mapper-locations:
    classpath*:  com/soiree/swagger/mapper/*.xml
#logging:   #如已使用了配置文件，请注释掉
    ##  level:
    ##    root: DEBUG #指定包，指定类，或者直接root  #root: debug







#
#  datasource:
#    b
#    break-after-acquire-failure: false
#    #设置获取连接出错时的自动重连次数
#    connection-error-retry-attempts: 1
##设置获取连接时的重试次数，-1为不重试
#    not-full-fimeout-retry-count: 2
#    #重连间隔时间 单位毫秒
#    acquire-retry-delay: 10000
#    # 设置获取连接出错时是否马上返回错误，true为马上返回
#    fail-fast: true
#      #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
#    #监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
#    filters: stat,wall




